export const siteConfig = {
  name: "IPTV USA Pro",
  shortName: "IPTV USA",
  title: "IPTV USA The Official IPTV Subscription Service",
  description:
    "Official IPTV USA subscription offering over 24,000+ live IPTV USA channels, 110,000+ movies, and TV shows. Get the best IPTV USA service with 4K FHD streaming, Anti Freeze servers, and 24/7 IPTV USA support on all devices.",
  url: "https://www.iptvusa-pro.com",
  domain: "www.iptvusa-pro.com",
  ogImage: "https://www.iptvusa-pro.com/og-image.png",
  supportEmail: "iptvusapro@gmail.com",
  supportPhone: "+1 (555) 349 8822",
  telegramUsername: "contactexe",
  links: {
    telegram: "https://t.me/contactexe",
  },
  googleSiteVerification: "9hVbuN1WeHJ3wZbAurex67uyWuD45Q98vnrzJTXLueg",
  keywords: [
    "IPTV USA",
    "IPTV USA Pro",
    "official IPTV USA",
    "best IPTV USA",
    "IPTV USA subscription",
    "best IPTV USA provider",
    "top IPTV USA",
    "IPTV subscription USA",
    "IPTV service USA",
    "buy IPTV USA",
    "IPTV USA login",
    "IPTV USA plans",
    "IPTV USA pricing",
    "cheap IPTV USA",
    "affordable IPTV USA subscription",
    "IPTV USA 4K",
    "IPTV USA live sports",
    "IPTV USA PPV fights",
    "IPTV USA no buffering",
    "IPTV USA Anti Freeze",
    "IPTV USA 24000 channels",
    "IPTV USA channels list",
    "IPTV USA VOD movies",
    "IPTV USA Firestick",
    "best IPTV USA for Firestick",
    "IPTV USA Smart TV",
    "IPTV USA Apple TV",
    "IPTV USA Android box",
    "IPTV USA TiviMate",
    "IPTV USA Smarters Pro",
    "IPTV USA Indian channels",
    "IPTV USA reseller",
    "IPTV USA reseller panel",
  ],
  stats: {
    channels: "+24,000",
    vod: "+110,000",
    uptime: "99.9%",
    activeUsers: "50,000+",
    satisfactionRate: "4.9/5",
  },
  serverLocations: [
    { city: "New York, USA", ping: "14ms", status: "Optimal" },
    { city: "Los Angeles, USA", ping: "18ms", status: "Optimal" },
    { city: "Chicago, USA", ping: "16ms", status: "Optimal" },
    { city: "Dallas, USA", ping: "15ms", status: "Optimal" },
    { city: "Miami, USA", ping: "17ms", status: "Optimal" },
    { city: "Toronto, Canada", ping: "22ms", status: "Optimal" },
  ],
};
