export const siteConfig = {
  name: "IPTV USA Pro",
  shortName: "IPTV USA",
  title: "IPTV USA The Official IPTV Subscription Service",
  description:
    "Official IPTV USA subscription offering over 24,000+ live IPTV USA channels, 110,000+ movies, and TV shows. Get the best IPTV USA service with 4K FHD streaming, Anti Freeze servers, and 24/7 IPTV USA support on all devices.",
  url: "https://www.iptvusa-pro.com",
  domain: "www.iptvusa-pro.com",
  ogImage: "https://www.iptvusa-pro.com/og-image.png",
  supportEmail: "iptvusapro@gmail.com",
  supportPhone: "+1 (555) 349 8822",
  telegramUsername: "contactexe",
  links: {
    telegram: "https://t.me/contactexe",
  },
  googleSiteVerification: "9hVbuN1WeHJ3wZbAurex67uyWuD45Q98vnrzJTXLueg",
  keywords: [
    // Core Brand & Authority
    "IPTV USA",
    "IPTV USA Pro",
    "IPTV USA official",
    "official IPTV USA",
    "IPTV USA official website",
    "IPTV USA official subscription",
    "best IPTV USA",
    "best IPTV USA 2026",
    "top rated IPTV USA",
    "best IPTV USA provider",
    "IPTV USA subscription",
    "IPTV subscription USA",
    "IPTV service USA",
    "buy IPTV USA",
    "IPTV USA login",
    "IPTV USA account",
    "IPTV USA review",
    "reliable IPTV USA",
    "stable IPTV USA service",
    "fastest IPTV USA",
    "legal IPTV USA subscription",

    // Commercial, Pricing & Packages
    "IPTV USA plans",
    "IPTV USA pricing",
    "cheap IPTV USA",
    "affordable IPTV USA subscription",
    "IPTV USA 1 month subscription",
    "IPTV USA 3 months subscription",
    "IPTV USA 6 months subscription",
    "IPTV USA 12 months subscription",
    "IPTV USA discount",
    "IPTV USA deals",
    "IPTV USA instant activation",
    "IPTV USA money back guarantee",
    "best value IPTV USA",

    // Technology & Streaming Performance
    "IPTV USA 4K",
    "IPTV USA UHD 60FPS",
    "IPTV USA FHD",
    "IPTV USA no buffering",
    "IPTV USA Anti Freeze",
    "IPTV USA Anti Freeze 9.3",
    "IPTV USA 10Gbps servers",
    "IPTV USA high speed streaming",
    "IPTV USA zero freezing",
    "IPTV USA M3U playlist link",
    "IPTV USA Xtream Codes API",
    "IPTV USA EPG TV guide",
    "IPTV USA 7 day catchup",

    // Channels, Live Sports & Content
    "IPTV USA 24000 channels",
    "IPTV USA channels list",
    "IPTV USA channel lineup",
    "IPTV USA 110000 VOD movies",
    "IPTV USA live sports",
    "IPTV USA PPV fights",
    "IPTV USA NFL live games",
    "IPTV USA NBA league games",
    "IPTV USA MLB live feeds",
    "IPTV USA NHL coverage",
    "IPTV USA UFC title fights",
    "IPTV USA boxing PPV",
    "IPTV USA Premier League",
    "IPTV USA Champions League",
    "IPTV USA college sports",
    "IPTV USA regional sports networks",
    "IPTV USA local news channels",
    "IPTV USA Indian channels",
    "IPTV USA Hindi Tamil Telugu channels",
    "IPTV USA Latino Spanish channels",
    "IPTV USA Canadian channels",
    "IPTV USA UK channels",

    // Devices & Applications
    "IPTV USA Firestick",
    "best IPTV USA for Firestick",
    "IPTV USA Fire TV 4K",
    "how to install IPTV USA on Firestick",
    "IPTV USA Downloader code",
    "IPTV USA Smart TV",
    "IPTV USA Samsung TV",
    "IPTV USA LG TV WebOS",
    "IPTV USA Apple TV",
    "IPTV USA iPhone iPad",
    "IPTV USA Android TV",
    "IPTV USA Android box",
    "IPTV USA Nvidia Shield",
    "IPTV USA Windows PC",
    "IPTV USA Mac",
    "IPTV USA TiviMate",
    "IPTV USA TiviMate premium",
    "IPTV USA Smarters Pro",
    "IPTV USA IBO Player",
    "IPTV USA XCIPTV",
    "IPTV USA Smart IPTV",
    "IPTV USA IPTVX",

    // Reseller & Business
    "IPTV USA reseller",
    "IPTV USA reseller panel",
    "buy IPTV USA credits",
    "IPTV reseller program USA",
    "IPTV USA wholesale credits",
    "IPTV USA Xtream Codes panel",
    "best IPTV reseller USA 2026",
  ],
  stats: {
    channels: "+24,000",
    vod: "+110,000",
    uptime: "99.9%",
    activeUsers: "50,000+",
    satisfactionRate: "4.9/5",
  },
  serverLocations: [
    { city: "New York, USA", ping: "14ms", status: "Optimal" },
    { city: "Los Angeles, USA", ping: "18ms", status: "Optimal" },
    { city: "Chicago, USA", ping: "16ms", status: "Optimal" },
    { city: "Dallas, USA", ping: "15ms", status: "Optimal" },
    { city: "Miami, USA", ping: "17ms", status: "Optimal" },
    { city: "Toronto, Canada", ping: "22ms", status: "Optimal" },
  ],
};
